apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::837241849244:role/eksctl-eksctl-demo-nodegroup-ng-1-NodeInstanceRole-IHQ0OJ3NT87V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::837241849244:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-14T14:31:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13979"
  uid: 2127fcae-3094-45c2-8d4e-a452d712c2d7
